apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  db-host: {{ .Values.app.environment.DB_HOST | b64enc | quote }}
  db-name: {{ .Values.app.environment.DB_NAME | b64enc | quote }}
  db-user: {{ .Values.app.environment.DB_USER | b64enc | quote }}
  db-pass: {{ .Values.app.environment.DB_PASS | b64enc | quote }}