apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: ghcr.io/skillfactory-devops/django-pg-docker-app:v0.0.2
        ports:
        - containerPort: {{ .Values.app.port }}
        env:
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: pg-host
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: pg-db
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: pg-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: pg-password

