apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  postgres-password: {{ .Values.postgres.password | b64enc | quote }}
  postgres-db: {{ .Values.postgres.dbName | b64enc | quote }}
  postgres-user: {{ .Values.postgres.user | b64enc | quote }}