app:
  port: 3003
  ingress:
    enabled: true
    host: zane.su
    path: /app
  environment:
    POSTGRES_HOST: postgres
    POSTGRES_DB: tutorial-dev
    POSTGRES_USER: vihnie
    POSTGRES_PASSWORD: password

postgres:
  image: postgres:13-alpine
  volumeSize: 2Gi
