name: Build & push image

on:
  push:
    branches: [ $default-branch ]
    tags: [ 'v*.*.*' ]
  workflow_call: # позволяет запускать пайплайн вручную через вкладку Actions
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build, Test, and Push Docker Image
    runs-on: self-hosted

    permissions:
      contents: read
      packages: write # Required for pushing to GHCR

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Log in to GitHub Container Registry
    - name: Log in to GitHub Container Registry (GHCR)
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Convert Repository Owner to Lowercase
      run: echo "REPO_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    # Get tags
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: ghcr.io/${{ env.REPO_OWNER }}/django-pg-docker-app

    - name: Build and Push Image to Registry
      uses: docker/build-push-action@v4
      with:
        context: django-pg-docker-app
        push: true
        load: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
